# Generated by Django 5.2.8 on 2026-05-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('Terminee', 'Terminée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectalert',
            name='alert_type',
            field=models.CharField(choices=[('PROGRESS', 'Progression bloquée'), ('COST', 'Coût stagnant'), ('DELAY', 'Risque de retard'), ('BUDGET', 'Budget dépassé'), ('EFFICIENCY', 'Faible efficacité'), ('FUTURE_INEFFICIENCY', 'Inefficacité future')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('Terminee', 'Terminée')], default='en_attente', max_length=20),
        ),
    ]
